### ISSUE TITLE
Scroll not working

### ISSUE THREAD

**Issue by xcarpentier** [michaeldzjap/react-pdf-sample#1]
Hi,

Thank you for your sample.
Unfortunately I can't test it correctly. The result to the top when going to the end.

Any idea why ?

![react-pdf-virtualize](https://user-images.githubusercontent.com/923036/40966665-622e7974-68b1-11e8-83d7-c2e3c50b1ea8.gif)

**Comment by michaeldzjap** [comment]
Not sure to be honest. Probably _react-virtualized_ related. I haven't updated the dependencies in a while. Hopefully that will solve it.

**Comment by ps06756** [comment]
I am also facing the same issue. Nope, it's not dependency related.

**Comment by ps06756** [comment]
Please check this working sample with the latest version of react-pdf + react-virtualized
https://gist.github.com/ps06756/7b0d71e04db0cfb1e56aeef0a6cebc2b

**Comment by michaeldzjap** [comment]
I have updated the example today. I switched to _react-window_. Apart from scrolling via the _react-window_ API (i.e. using `scrollToItem()`) I think it should work again.
