### ISSUE TITLE
missing ) after argument list

### ISSUE THREAD

**Issue by AndrejsCistoserdovs** [michaeldzjap/react-pdf-sample#2]
Hi

I cloned the sample project and getting the following error when running npm script:

$ npm run prod

> react-pdf-sample@1.0.0 prod C:\Projects\react-pdf-sample
> node -r @babel/register ./node_modules/.bin/webpack --progress --hide-modules --config webpack.prod.js

C:\Projects\react-pdf-sample\node_modules\.bin\webpack:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^
SyntaxError: missing ) after argument list

**Comment by michaeldzjap** [comment]
I'm not quite sure, but that seems to be a webpack specific error, perhaps in combination with usage on Windows? I am not really able to help you much here, as I am not on Windows myself. I can run `npm run prod` here locally on OSX without a problem.

Only thing I can suggest is to delete your node_modules folder and install all dependencies again. Hopefully that works.
