### ISSUE TITLE
Whole pdf gets rendered because height is set to containerHeight (also explains why scrollToItem does not work)

### ISSUE THREAD

**Issue by LuccaHellriegel** [michaeldzjap/react-pdf-sample#7]
_TL.DR: height=containerHeight leads to the whole document being rendered at once. Height should only be of the visible part of the list. Because the whole document is rendered "scrollToItem" does not work, because all items are already "visible" and scrolling them into the visible-area does nothing because they already are there._

Hello! 

First of all, I would like to thank you very much for this sample-project. It was a very informative and helpful jump-off point for using react-pdf with react-window in my own project.

After a couple of days of trying to improve the performance of the presented approach (my project uses additional UI-elements which killed the performance without any apparent reason), I think I found a critical bug that also explains why scrollToItem does not work.

In Viewer.js the height is set incorrectly. Setting height=containerHeight leads to the whole document being rendered at once, not actually using the windowing approach.

From the react-window docs:

> height: number | string
> Height of the list.
>
> For vertical lists, this must be a number. It affects the number of rows that will be rendered (and displayed) at any given time.

I think this is formulated slightly misleading (the first sentence at least). This is not the height of the full list / the container, this is the height of the list that we want to actually show - the "window" if you will, the visible part. Setting this to the full document-height leads to the full document being rendered - skipping the optimizations that react-window offers. 

A better height might be just the viewport height. Like this:
`
<VariableSizeList
							height={window.innerHeight}
							...
						</VariableSizeList>
`
(Of course this would need to be extracted to a variable and then changed on resize-events etc.)

Testing it with this leads to scrollToItem working correctly and an increased performance when using this combination with other UI-elements.

Sadly I dont have time to do a proper PR right now, but I still thought this might be interesting.

All the best,
Lucca

**Comment by michaeldzjap** [comment]
@LuccaHellriegel That's definitely interesting. Thanks for sharing your findings! I don't think I will have much time myself to really look into this on short notice, but I will keep it in mind.

**Comment by michaeldzjap** [comment]
I had some time today to try out your suggestions @LuccaHellriegel and I think I managed to fix the problem. Scrolling to a page is working now as well. Thanks again!
